query GetUsers @auth(level: PUBLIC) {
  users{
    userId
    displayName
    email
    photoUrl
    createdAt
  }
}

query GetUser($userId: UUID!) @auth(level: PUBLIC) {
  user(first: {where: {userId: {eq: $userId}}}) {
    userId
    displayName
    email
    photoUrl
    createdAt
  }
}