extend type Event {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Event", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Event`.`creator`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  creatorId: UUID! @fdc_generated(from: "Event.creator", purpose: IMPLICIT_REF_FIELD)
}
extend type EventInstance {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "EventInstance", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `EventInstance`.`event`. It must match the value of `Event`.`id`. See `@ref` for how to customize it.
  """
  eventId: UUID! @fdc_generated(from: "EventInstance.event", purpose: IMPLICIT_REF_FIELD)
}
extend type RecurringEvent {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "RecurringEvent", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `RecurringEvent`.`event`. It must match the value of `Event`.`id`. See `@ref` for how to customize it.
  """
  eventId: UUID! @fdc_generated(from: "RecurringEvent.event", purpose: IMPLICIT_REF_FIELD)
}
extend type Registration {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Registration", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Registration`.`eventInstance`. It must match the value of `EventInstance`.`id`. See `@ref` for how to customize it.
  """
  eventInstanceId: UUID! @fdc_generated(from: "Registration.eventInstance", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Registration`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Registration.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
